# Generated by Django 5.2.7 on 2025-11-01 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.UUID('ea4dabc4-8e56-4a80-baab-8f1939d8d626'), editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('task_text', models.TextField()),
                ('task_font', models.TextField(blank=True, null=True)),
                ('task_color', models.TextField(blank=True, null=True)),
                ('task_shirt_colors', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('text_color', models.TextField(blank=True, null=True)),
                ('shirt_color', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockups_api.mockuptask')),
            ],
        ),
    ]
