# Generated by Django 5.2.7 on 2025-11-01 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptask',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('db411632-9dc2-4a85-ac0e-e16113f03c75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
