# Generated by Django 5.2.7 on 2025-11-01 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups_api', '0002_alter_mockuptask_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockuptask',
            old_name='task_font',
            new_name='font',
        ),
        migrations.RenameField(
            model_name='mockuptask',
            old_name='task_shirt_colors',
            new_name='shirt_colors',
        ),
        migrations.RenameField(
            model_name='mockuptask',
            old_name='task_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='mockuptask',
            old_name='task_color',
            new_name='text_color',
        ),
        migrations.AlterField(
            model_name='mockuptask',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('5c750c58-75f1-430a-b05d-3d2aa9732a04'), editable=False, primary_key=True, serialize=False),
        ),
    ]
