# Generated by Django 5.2.7 on 2025-11-01 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups_api', '0003_rename_task_font_mockuptask_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptask',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('471b5cc4-90f4-4105-b1f8-9e98d3dc6053'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
