# Generated by Django 5.2.7 on 2025-11-02 14:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mockups_api", "0004_alter_mockuptask_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mockuptask",
            old_name="shirt_colors",
            new_name="shirt_color",
        ),
        migrations.AddField(
            model_name="mockuptask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mockuptask",
            name="result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mockup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mockuptask",
            name="task_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
